package iac

import (
	"strings"
	"testing"
	"time"
)

func sample() *Inventory {
	inv := &Inventory{}
	inv.Add(Host{Name: "lab-app-01", VMID: 210, Node: "pve", IP: "192.0.2.210", User: "ops", Groups: []string{"lab", "lab_apps"}})
	inv.Add(Host{Name: "lab-app-02", VMID: 211, Node: "pve", IP: "192.0.2.211", User: "ops", Groups: []string{"lab"}})
	return inv
}

// The generated file has to be droppable in place of the hand-written
// docs/infra/ansible/inventory.example.yml — same nesting, same keys, same
// two-space indent. A shape that only Ansible can read but no human recognises
// would defeat the point of generating it.
func TestYAMLMatchesTheShapeOfTheExampleInventory(t *testing.T) {
	inv := sample()
	inv.Resolve()

	out, err := inv.RenderYAML("")
	if err != nil {
		t.Fatal(err)
	}

	want := `all:
  children:
    lab:
      hosts:
        lab-app-01:
          ansible_host: 192.0.2.210
          ansible_user: ops
        lab-app-02:
          ansible_host: 192.0.2.211
          ansible_user: ops
    lab_apps:
      hosts:
        lab-app-01:
          ansible_host: 192.0.2.210
          ansible_user: ops
`
	if got := string(out); got != want {
		t.Errorf("inventaire produit :\n%s\nattendu :\n%s", got, want)
	}
}

// Two runs over the same fleet must produce the same bytes.
//
// This is not cosmetic. The inventory is written to a file an operator diffs
// and a CI job caches; a document that reshuffles itself because Go iterates
// maps in random order would show a change at every generation, and real
// changes would stop being visible among the noise.
func TestRenderingIsDeterministic(t *testing.T) {
	for _, render := range map[string]func(*Inventory) ([]byte, error){
		"yaml": func(i *Inventory) ([]byte, error) { return i.RenderYAML("") },
		"json": func(i *Inventory) ([]byte, error) { return i.RenderJSON() },
	} {
		first, err := render(sample())
		if err != nil {
			t.Fatal(err)
		}
		for i := 0; i < 20; i++ {
			again, err := render(sample())
			if err != nil {
				t.Fatal(err)
			}
			if string(again) != string(first) {
				t.Fatalf("deux générations diffèrent :\n%s\n---\n%s", first, again)
			}
		}
	}
}

// PVE and Ansible do not agree on what a name may contain. A tag Ansible would
// choke on has to be translated, not passed through.
func TestGroupNameTranslatesWhatAnsibleRefuses(t *testing.T) {
	cases := map[string]string{
		"lab_apps": "lab_apps",
		// A dash parses as a subtraction inside {{ groups.lab-apps }}.
		"lab-apps": "lab_apps",
		"prod.eu":  "prod_eu",
		// A group name may not start with a digit, for the same reason.
		"01-web": "_01_web",
		"":       "",
		"  ":     "",
	}
	for tag, want := range cases {
		if got := GroupName(tag); got != want {
			t.Errorf("GroupName(%q) = %q, attendu %q", tag, got, want)
		}
	}
}

// PVE enforces uniqueness on vmid, not on name. An inventory keyed by name
// would lose the second of two guests called the same thing — and lose it
// silently, which is the only unacceptable part.
func TestDuplicateNamesAreKeptAndReported(t *testing.T) {
	inv := &Inventory{}
	inv.Add(Host{Name: "web", VMID: 130, IP: "192.0.2.130"})
	inv.Add(Host{Name: "web", VMID: 131, IP: "192.0.2.131"})
	inv.Add(Host{Name: "seul", VMID: 132, IP: "192.0.2.132"})

	renamed := inv.Resolve()
	if len(renamed) != 2 {
		t.Fatalf("les deux doublons doivent être signalés, reçu : %v", renamed)
	}

	names := map[string]bool{}
	for _, h := range inv.Hosts {
		names[h.Name] = true
	}
	for _, want := range []string{"web-130", "web-131", "seul"} {
		if !names[want] {
			t.Errorf("hôte %q absent de l'inventaire : %v", want, names)
		}
	}
}

// A host that belongs to no group must still appear somewhere. Filtered out of
// every group, it is a machine Ansible will never configure and nobody will
// notice — the failure this whole command exists to prevent.
func TestAHostWithNoGroupIsNotLost(t *testing.T) {
	inv := &Inventory{}
	inv.Add(Host{Name: "orpheline", VMID: 140, IP: "192.0.2.140"})
	inv.Resolve()

	out, err := inv.RenderYAML("")
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(out), UngroupedName) || !strings.Contains(string(out), "orpheline") {
		t.Errorf("l'hôte sans tag doit atterrir dans « %s » :\n%s", UngroupedName, out)
	}
}

// The banner has to say three things: who wrote the file, that it must not be
// edited, and when — a stale inventory points Ansible at an address the DHCP
// lease has since moved.
func TestHeaderCarriesToolProhibitionAndDate(t *testing.T) {
	h := Header("https://pve.example:8006", time.Date(2026, 7, 31, 18, 4, 5, 0, time.UTC))

	for _, want := range []string{"GENERATED BY pvectl", "DO NOT EDIT", "2026-07-31T18:04:05Z", "https://pve.example:8006"} {
		if !strings.Contains(h, want) {
			t.Errorf("l'en-tête ne contient pas %q :\n%s", want, h)
		}
	}
}
