package cmd

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/MakFly/pvectl/internal/testutil"
)

// inventoryRoutes describes a lab with one of every case the generator has to
// deal with, taken from the real /cluster/resources?type=vm of the lab node:
//
//	lxc/120    a container       — no QEMU agent
//	qemu/211   running, answers  — the only host that makes it in
//	qemu/212   running, silent   — its agent route is deliberately absent
//	qemu/213   stopped           — nothing to interrogate
//	qemu/9000  a template        — not a host
func inventoryRoutes() map[string]string {
	return map[string]string{
		"GET /api2/json/cluster/resources":                               "cluster-resources-vm.json",
		"GET /api2/json/nodes/pve/qemu/211/agent/network-get-interfaces": "agent-ifaces.json",
		"GET /api2/json/nodes/pve/qemu/211/config":                       "qemu-config.json",
	}
}

// The inventory carries an address the guest reported, and only that.
func TestInventoryTakesItsAddressFromTheAgent(t *testing.T) {
	srv := testutil.New(t, "../testdata", inventoryRoutes())
	point(t, srv.URL)

	stdout, _, err := run(t, "iac", "inventory", "--node", "pve")
	if err != nil {
		t.Fatalf("iac inventory a échoué : %v", err)
	}

	for _, want := range []string{
		"GENERATED BY pvectl",
		"lab:",                 // the group comes from the PVE tag
		"lab-app-01:",          // the host is named after the guest
		"203.0.113.10",         // the address the agent reported
		"ansible_user: debian", // read from cloud-init's ciuser
	} {
		if !strings.Contains(stdout, want) {
			t.Errorf("l'inventaire ne contient pas %q :\n%s", want, stdout)
		}
	}
}

// The criterion that matters most in this story: nothing is dropped in silence.
//
// Each of these four guests is absent from the document for a different reason,
// and an operator who cannot see the reason will conclude the fleet is smaller
// than it is.
func TestExcludedGuestsAreNamedOnStderr(t *testing.T) {
	srv := testutil.New(t, "../testdata", inventoryRoutes())
	point(t, srv.URL)

	stdout, stderr, err := run(t, "iac", "inventory", "--node", "pve")
	if err != nil {
		t.Fatal(err)
	}

	cases := map[string]string{
		"120":  "conteneur LXC",
		"212":  "agent QEMU muet",
		"213":  "arrêtée",
		"9000": "template",
	}
	for vmid, reason := range cases {
		if !strings.Contains(stderr, "exclu "+vmid) || !strings.Contains(stderr, reason) {
			t.Errorf("le guest %s doit être exclu ET expliqué (%q) :\n%s", vmid, reason, stderr)
		}
		if strings.Contains(stdout, "vmid: "+vmid) {
			t.Errorf("le guest %s exclu ne doit pas figurer dans le document", vmid)
		}
	}
}

// stdout carries the document, stderr everything else. Otherwise
// `pvectl iac inventory > inv.yml` writes a file Ansible cannot parse.
func TestOnlyTheDocumentGoesToStdout(t *testing.T) {
	srv := testutil.New(t, "../testdata", inventoryRoutes())
	point(t, srv.URL)

	stdout, _, err := run(t, "iac", "inventory", "--node", "pve")
	if err != nil {
		t.Fatal(err)
	}
	if strings.Contains(stdout, "exclu ") {
		t.Errorf("une explication a fui sur stdout :\n%s", stdout)
	}
	if !strings.HasPrefix(stdout, "#") {
		t.Errorf("stdout doit commencer par l'en-tête généré :\n%s", stdout)
	}
}

func TestInventoryUserFlagOverridesCloudInit(t *testing.T) {
	srv := testutil.New(t, "../testdata", inventoryRoutes())
	point(t, srv.URL)

	stdout, _, err := run(t, "iac", "inventory", "--node", "pve", "--user", "ops")
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(stdout, "ansible_user: ops") {
		t.Errorf("--user doit l'emporter sur ciuser :\n%s", stdout)
	}
	// And the config read becomes pointless, so it must not happen.
	for _, req := range srv.Requests {
		if strings.HasSuffix(req, "/qemu/211/config") {
			t.Errorf("--user fourni : la configuration cloud-init n'a pas à être lue (%v)", srv.Requests)
		}
	}
}

func TestInventoryTagFilter(t *testing.T) {
	srv := testutil.New(t, "../testdata", inventoryRoutes())
	point(t, srv.URL)

	stdout, stderr, err := run(t, "iac", "inventory", "--node", "pve", "--tag", "pvectl")
	if err != nil {
		t.Fatal(err)
	}
	// Only the container carries « pvectl »; it is filtered in, then excluded
	// for having no agent — so the document is empty and says so.
	if strings.Contains(stdout, "lab-app-01") {
		t.Errorf("--tag pvectl ne doit pas retenir lab-app-01 :\n%s", stdout)
	}
	if !strings.Contains(stderr, "aucun hôte") {
		t.Errorf("un inventaire vide doit le dire :\n%s", stderr)
	}
}

func TestInventoryWritesTheFileAndKeepsStdoutClean(t *testing.T) {
	srv := testutil.New(t, "../testdata", inventoryRoutes())
	point(t, srv.URL)

	path := filepath.Join(t.TempDir(), "inventory.yml")
	stdout, stderr, err := run(t, "iac", "inventory", "--node", "pve", "-o", path)
	if err != nil {
		t.Fatal(err)
	}
	if stdout != "" {
		t.Errorf("avec -o, stdout doit rester vide : %q", stdout)
	}
	if !strings.Contains(stderr, path) {
		t.Errorf("stderr doit dire où le fichier a été écrit : %q", stderr)
	}

	body, err := os.ReadFile(path) //nolint:gosec // path built by the test
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(body), "203.0.113.10") {
		t.Errorf("le fichier écrit ne contient pas l'inventaire :\n%s", body)
	}
}

// --format json is the same tree, not a second document. `ansible-inventory -i`
// reads it because JSON is a subset of YAML.
func TestInventoryJSONCarriesTheSameTree(t *testing.T) {
	srv := testutil.New(t, "../testdata", inventoryRoutes())
	point(t, srv.URL)

	stdout, _, err := run(t, "iac", "inventory", "--node", "pve", "--format", "json")
	if err != nil {
		t.Fatal(err)
	}
	for _, want := range []string{`"all"`, `"children"`, `"lab"`, `"ansible_host": "203.0.113.10"`} {
		if !strings.Contains(stdout, want) {
			t.Errorf("le JSON ne contient pas %s :\n%s", want, stdout)
		}
	}
}

// stubTool puts a fake binary first in PATH and records how it was called.
//
// The wrapped tools are installed on the machine this was written on; the stub
// exists to make the invocation observable, not to avoid the dependency.
func stubTool(t *testing.T, name, stdout string) (calls string) {
	t.Helper()

	dir := t.TempDir()
	calls = filepath.Join(dir, "calls")
	script := "#!/bin/sh\n" +
		"{ printf 'argv: %s\\n' \"$*\"; printf 'TF_VAR_proxmox_api_token=%s\\n' \"$TF_VAR_proxmox_api_token\"; } >> " + calls + "\n" +
		"printf '%s\\n'\n"
	if stdout != "" {
		script = "#!/bin/sh\n" +
			"{ printf 'argv: %s\\n' \"$*\"; printf 'TF_VAR_proxmox_api_token=%s\\n' \"$TF_VAR_proxmox_api_token\"; } >> " + calls + "\n" +
			"cat <<'EOS'\n" + stdout + "\nEOS\n"
	}
	if err := os.WriteFile(filepath.Join(dir, name), []byte(script), 0o755); err != nil { //nolint:gosec // a test stub must be executable
		t.Fatal(err)
	}
	t.Setenv("PATH", dir+string(os.PathListSeparator)+os.Getenv("PATH"))
	return calls
}

// The criterion of PVX-046: the token reaches Terraform through the
// environment, and never through terraform.tfvars. A secret in a file gets
// committed — this project refuses it in its OWN config file, and has no reason
// to be more relaxed about someone else's.
func TestTheTokenReachesTerraformThroughTheEnvironmentOnly(t *testing.T) {
	tfDir := t.TempDir()
	calls := stubTool(t, "terraform", `{"format_version":"1.0"}`)

	cfg := filepath.Join(t.TempDir(), "config.yaml")
	if err := os.WriteFile(cfg, []byte(
		"current_context: test\ncontexts:\n  test:\n    iac:\n      terraform_dir: "+tfDir+"\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	t.Setenv("PVECTL_CONFIG", cfg)
	t.Setenv("TF_VAR_proxmox_api_token", "")

	srv := testutil.New(t, "../testdata", map[string]string{
		"GET /api2/json/version": "version.json",
	})
	point(t, srv.URL)

	if _, _, err := run(t, "iac", "plan", "--node", "pve"); err != nil {
		t.Fatalf("iac plan : %v", err)
	}

	body, err := os.ReadFile(calls) //nolint:gosec // path built by the test
	if err != nil {
		t.Fatal(err)
	}
	got := string(body)

	if !strings.Contains(got, "TF_VAR_proxmox_api_token=automation@pve!pvectl=s3cr3t") {
		t.Errorf("le token doit arriver par l'environnement, au format <token-id>=<secret> :\n%s", got)
	}
	if !strings.Contains(got, "argv: plan") {
		t.Errorf("terraform doit être appelé en « plan » :\n%s", got)
	}
	// Nothing was written next to the .tf files.
	entries, err := os.ReadDir(tfDir)
	if err != nil {
		t.Fatal(err)
	}
	if len(entries) != 0 {
		t.Errorf("pvectl n'écrit rien dans le dossier terraform : %v", entries)
	}
}

// --dry-run on apply runs plan. Anything else would make the flag a promise the
// command does not keep.
func TestApplyDryRunRunsPlan(t *testing.T) {
	tfDir := t.TempDir()
	calls := stubTool(t, "terraform", `{"format_version":"1.0"}`)

	cfg := filepath.Join(t.TempDir(), "config.yaml")
	if err := os.WriteFile(cfg, []byte(
		"current_context: test\ncontexts:\n  test:\n    iac:\n      terraform_dir: "+tfDir+"\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	t.Setenv("PVECTL_CONFIG", cfg)

	srv := testutil.New(t, "../testdata", map[string]string{"GET /api2/json/version": "version.json"})
	point(t, srv.URL)

	if _, _, err := run(t, "iac", "apply", "--dry-run", "--node", "pve"); err != nil {
		t.Fatalf("iac apply --dry-run : %v", err)
	}

	body, _ := os.ReadFile(calls) //nolint:gosec // path built by the test
	if strings.Contains(string(body), "argv: apply") {
		t.Errorf("--dry-run ne doit jamais lancer « apply » :\n%s", body)
	}
	if !strings.Contains(string(body), "argv: plan") {
		t.Errorf("--dry-run doit lancer « plan » :\n%s", body)
	}
}
